env:
  TERM: xterm-256color

font:
  normal:
    family: Terminess Nerd Font
    style: Medium

  bold:
    family: Terminess Nerd Font
    style: Bold

  italic:
    family: Terminess Nerd Font
    style: Medium Italic

  bold_italic:
    family: Terminess Nerd Font
    style: Bold Italic

  size: 14

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
  - { key: F, mods: Control, action: SearchForward }
  - { key: V, mods: Super, action: Paste }

selection:
  save_to_clipboard: true
