local saves={
    "nicotine",
    "",
    "bilbo",
    "",
    "mozilla-firebird",
    "bilbo",
    "",
    "bilbo",
    "",
    "bilbo",
    "",
    "nicotine",
    "",
    "mozilla-firebird",
    "",
    "mozilla-firebird",
    "bilbo",
    "",
    "k3b",
    "bilbo",
    "",
    "mozilla-firebird",
    "bilbo",
    "",
    "bilbo",
    "",
    "mozilla-firebird",
    "bilbo",
    "",
    "mozilla-firebird",
    "",
    "mozilla",
    "",
    "mozilla",
    "",
    "mozilla",
    "",
    "mozilla",
    "",
    "bilbo",
    "mozilla",
    "",
    "mozilla",
    "xnest",
    "",
    "hendry@scrooge-15: /home/hendry<1>",
    "hendry@scrooge-15: /home/hendry",
    "test",
    "",
    "mozilla ",
    "straw",
    "mozilla",
    "",
    "mozilla",
}
for k=table.getn(saves),1,-1 do query_history_push(saves[k]) end
