# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.search.defaultengine", "engine:///usr/lib/mozilla/searchplugins/NetscapeSearch.src");
user_pref("browser.startup.homepage", "http://www.cs.helsinki.fi/u/hendry/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.5");
user_pref("dom.disable_open_during_load", true);
user_pref("intl.charsetmenu.browser.cache", "windows-1250, UTF-8, ISO-8859-1");
user_pref("plugin.soname.list", "libXt.so:libXext.so");
user_pref("prefs.converted-to-utf8", true);
user_pref("privacy.popups.first_popup", false);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("security.warn_submit_insecure", false);
user_pref("signon.SignonFileName", "70572827.s");
user_pref("timebomb.first_launch_time", "1070540841017589");
user_pref("update_notifications.provider.0.last_checked", 1071751776);
