# Mozilla User Preferences
// This is a generated file!

user_pref("browser.download.dir", "/home/hendry/personal/jutta-flight-march-2004");
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.history.last_page_visited", "http://www.faqs.org/docs/bashman/bashref_toc.html#SEC_Contents");
user_pref("browser.search.defaultengine", "engine:///usr/lib/mozilla/searchplugins/google.src");
user_pref("browser.search.opensidebarsearchpanel", false);
user_pref("browser.startup.homepage", "http://www.cs.helsinki.fi/u/hendry/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.2.1");
user_pref("browser.tabs.loadInBackground", true);
user_pref("browser.tabs.opentabfor.middleclick", true);
user_pref("browser.toolbars.showbutton.print", false);
user_pref("dom.disable_image_src_set", true);
user_pref("dom.disable_open_during_load", true);
user_pref("dom.disable_window_flip", true);
user_pref("dom.disable_window_move_resize", true);
user_pref("dom.disable_window_open_feature.status", true);
user_pref("dom.disable_window_status_change", true);
user_pref("editor.history_title_0", "CSS Diagrams");
user_pref("editor.history_title_1", "ESN HYY/Helsinki");
user_pref("editor.history_url_0", "http://www.surfare.net/~toolman/temp/diagram.html");
user_pref("editor.history_url_1", "http://www.helsinki.fi/jarj/snvk/Linda/ESN/");
user_pref("ext.checky.pref.agent.w3c.link", true);
user_pref("ext.checky.pref.agent.wdg.css", true);
user_pref("ext.checky.pref.agent.webthing.accessibility", true);
user_pref("ext.checky.pref.agent.webthing.page", true);
user_pref("ext.checky.pref.global.tempdirectory", "/home/hendry/.mozilla/default/ack41g03.slt");
user_pref("intl.accept_languages", "");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, windows-1250, windows-1254, windows-1252, ISO-8859-15");
user_pref("intl.charsetmenu.composer.cache", "ISO-8859-1");
user_pref("ldap_2.prefs_migrated", true);
user_pref("network.cookie.cookieBehavior", 0);
user_pref("network.cookie.p3p", "frfradaa");
user_pref("network.cookie.p3plevel", 2);
user_pref("network.ftp.anonymous_password", "");
user_pref("plugin.soname.list", "libXt.so:libXext.so");
user_pref("prefs.converted-to-utf8", true);
user_pref("privacy.popups.first_popup", false);
user_pref("privacy.popups.remove_blacklist", false);
user_pref("security.disable_button.changePassword", false);
user_pref("security.disable_button.resetPassword", false);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
user_pref("signon.SignonFileName", "70572827.s");
user_pref("timebomb.first_launch_time", "1070540841017589");
user_pref("update_notifications.provider.0.last_checked", 1073255749);
user_pref("wallet.SchemaValueFileName", "70706990.w");
user_pref("wallet.captureForms", false);
user_pref("wallet.caveat", true);
